name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      id: run-tests
      run: |
        cd src
        python -m pytest calculator.py | tee test-output.log

    - name: Summarize logs
      id: summarize
      run: |
        LOGS=$(cat test-output.log)
        curl -X POST https://api.openai.com/v1/engines/davinci-codex/completions \
        -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{
          "prompt": "Summarize the following logs:\n\n'"$LOGS"'",
          "max_tokens": 100
        }' > summary.json

    - name: Output summary
      run: |
        cat summary.json
